### 这题很简单，对随机生成并且打乱的arr从小到大依次进行冒泡排序，快速排序，插入排序和希尔排序算法的补全，并跑通代码，保留log信息（完成一种排序可得25分）

温馨提示：如使用sorded()等函数，按照0分计。


In [1]:
# 随机生成
import numpy as np

#请把冒泡排序算法补充完整
def bubble_sort(nums):
    '''
    代码补充
    '''
    for i in range(len(nums)):
        for j in range(len(nums)-i-1):
            if nums[j]>nums[j+1]:
                nums[j],nums[j+1]=nums[j+1],nums[j]
    return nums
if __name__ == '__main__':
    # 打乱顺序并随机生成
    nums=np.random.permutation(20)
    print(bubble_sort(nums))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
# 随机生成
import numpy as np

#请把快速排序算法补充完整
def quickSort(arr,low,high):
    '''
    代码补充
    '''
    def reSort(arr,low,high):
        res=low-1

        for j in range(low,high+1):
            if arr[j]<=arr[high]:
                res+=1
                arr[res],arr[j]=arr[j],arr[res]
        return res
    
    def random_index(arr,low,high):
        mid=low+(high-low)//2
        arr[high],arr[mid]=arr[mid],arr[high]
        return reSort(arr,low,high)
    
    if low<high:
        index=random_index(arr,low,high)
        quickSort(arr,low,index-1)
        quickSort(arr,index+1,high)
    return arr

if __name__ == '__main__':
    nums=np.random.permutation(20)
    import sys   
    sys.setrecursionlimit(1000) 
    print(quickSort(nums,0,len(nums)-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
# 随机生成
import numpy as np

#请把希尔排序算法补充完整
def shellSort(arr):
    '''
    代码补充
    '''
    size=len(arr)
    gap=size//2
    while gap>0:
        for i in range(gap,size):
            temp=arr[i]
            j=i
            while j>=gap and arr[j-gap]>temp:
                arr[j]=arr[j-gap]
                j-=gap
            arr[j]=temp
        gap=gap//2
    return arr
if __name__ == '__main__':
    
    nums=np.random.permutation(20)
    print(shellSort(nums))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
# 随机生成
import numpy as np

#请把插入排序算法补充完整
def insertionSort(arr):
    '''
    代码补充
    '''
    for i in range(1,len(arr)):
        temp=arr[i]
        j=i
        while j>0 and arr[j-1]>temp:
            arr[j]=arr[j-1]
            j-=1
        arr[j]=temp
    return arr
if __name__ == '__main__':
    
    nums=np.random.permutation(20)
    print(insertionSort(nums))  

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
